In [2]:
import pandas as pd
import billboard

In [3]:
chart = billboard.ChartData('hot-100')

In [4]:
print(chart)

hot-100 chart from 2019-07-06
-----------------------------
1. 'Old Town Road' by Lil Nas X Featuring Billy Ray Cyrus
2. 'Senorita' by Shawn Mendes & Camila Cabello
3. 'Bad Guy' by Billie Eilish
4. 'Talk' by Khalid
5. 'I Don't Care' by Ed Sheeran & Justin Bieber
6. 'Sucker' by Jonas Brothers
7. 'Suge' by DaBaby
8. 'Money In The Grave' by Drake Featuring Rick Ross
9. 'No Guidance' by Chris Brown Featuring Drake
10. 'Wow.' by Post Malone
11. 'Truth Hurts' by Lizzo
12. 'Sunflower (Spider-Man: Into The Spider-Verse)' by Post Malone & Swae Lee
13. 'You Need To Calm Down' by Taylor Swift
14. 'If I Can't Have You' by Shawn Mendes
15. 'Dancing With A Stranger' by Sam Smith & Normani
16. 'Panini' by Lil Nas X
17. 'Without Me' by Halsey
18. 'God's Country' by Blake Shelton
19. 'Pop Out' by Polo G Featuring Lil Tjay
20. 'MEGATRON' by Nicki Minaj
21. 'Sweet But Psycho' by Ava Max
22. 'Rodeo' by Lil Nas X & Cardi B
23. '7 Rings' by Ariana Grande
24. 'Hey Look Ma, I Made It' by Panic! At The Disco
25. 'Happier' by Marshmello & Bastille
26. 'Rumor' by Lee Brice
27. 'Never Really Over' by Katy Perry
28. 'Whiskey Glasses' by Morgan Wallen
29. 'The Git Up' by Blanco Brown
30. 'The London' by Young Thug, J. Cole & Travis Scott
31. 'ME!' by Taylor Swift Featuring Brendon Urie
32. 'High Hopes' by Panic! At The Disco
33. 'Beer Never Broke My Heart' by Luke Combs
34. 'Act Up' by City Girls
35. 'Eastside' by benny blanco, Halsey & Khalid
36. 'Middle Child' by J. Cole
37. 'Con Calma' by Daddy Yankee & Katy Perry Featuring Snow
38. 'Pure Water' by Mustard & Migos
39. 'Cross Me' by Ed Sheeran Featuring Chance The Rapper & PnB Rock
40. 'Going Bad' by Meek Mill Featuring Drake
41. 'Better' by Khalid
42. 'Shallow' by Lady Gaga & Bradley Cooper
43. 'Press' by Cardi B
44. 'Speechless' by Dan + Shay
45. 'Sicko Mode' by Travis Scott
46. 'Earfquake' by Tyler, The Creator
47. 'Look Back At It' by A Boogie Wit da Hoodie
48. 'Shotta Flow' by NLE Choppa
49. 'Break Up With Your Girlfriend, I'm Bored' by Ariana Grande
50. 'Nightmare' by Halsey
51. 'Ran$om' by Lil Tecca
52. 'Go Loko' by YG, Tyga & Jon Z
53. 'Someone You Loved' by Lewis Capaldi
54. 'Look What God Gave Her' by Thomas Rhett
55. 'Cool' by Jonas Brothers
56. 'Clout' by Offset Featuring Cardi B
57. 'One Thing Right' by Marshmello & Kane Brown
58. 'Good As You' by Kane Brown
59. 'Worth It' by YK Osiris
60. 'Just Us' by DJ Khaled Featuring SZA
61. 'Knockin' Boots' by Luke Bryan
62. 'Walk Me Home' by P!nk
63. 'GIRL' by Maren Morris
64. 'Easier' by 5 Seconds Of Summer
65. 'Please Me' by Cardi B & Bruno Mars
66. 'Some Of It' by Eric Church
67. 'All To Myself' by Dan + Shay
68. 'Callaita' by Bad Bunny & Tainy
69. '24/7' by Meek Mill Featuring Ella Mai
70. 'It's You' by Ali Gatie
71. 'Rearview Town' by Jason Aldean
72. 'Out The Mud' by Lil Baby Featuring Future
73. 'Call You Mine' by The Chainsmokers & Bebe Rexha
74. 'Girls Need Love' by Summer Walker X Drake
75. 'Soltera' by Lunay, Daddy Yankee & Bad Bunny
76. 'Talk You Out Of It' by Florida Georgia Line
77. 'Trampoline' by SHAED
78. 'Bacc At It Again' by Yella Beezy, Gucci Mane & Quavo
79. 'Before I Let Go' by Beyonce
80. 'Wish Wish' by DJ Khaled Featuring Cardi B & 21 Savage
81. 'Raised On Country' by Chris Young
82. 'Wake Up' by Travis Scott
83. 'Otro Trago' by Sech Featuring Darell
84. 'Eyes On You' by Chase Rice
85. 'La La Land' by Bryce Vine Featuring YG
86. 'Ocean Eyes' by Billie Eilish
87. 'Here With Me' by Marshmello Featuring CHVRCHES
88. 'Love Someone' by Brett Eldredge
89. 'Sanguine Paradise' by Lil Uzi Vert
90. 'Love Ain't' by Eli Young Band
91. 'Calma' by Pedro Capo X Farruko
92. 'Only Human' by Jonas Brothers
93. 'The Ones That Didn't Make It Back Home' by Justin Moore
94. 'Big Ole Freak' by Megan Thee Stallion
95. 'Tap' by NAV Featuring Meek Mill
96. 'You Stay' by DJ Khaled Featuring Meek Mill, J Balvin, Lil Baby & Jeremih
97. 'Baila Baila Baila' by Ozuna x Daddy Yankee x J Balvin x Farruko x Anuel AA
98. 'Cash Shit' by Megan Thee Stallion Featuring DaBaby
99. 'Omerta' by Drake
100. 'Summer Days' by Martin Garrix Featuring Macklemore & Patrick Stump

In [5]:
title_list=[]
artist_list=[]
date_list=[]

while chart.previousDate>"2018": 
    if chart[0].title not in title_list: 
        title_list.append(chart[0].title)
        artist_list.append(chart[0].artist)
        date_list.append(chart.previousDate)
    chart = billboard.ChartData('hot-100', chart.previousDate)

In [6]:
print(title_list)

['Old Town Road', '7 Rings', 'Sucker', 'Shallow', 'Without Me', 'Sunflower (Spider-Man: Into The Spider-Verse)', 'Thank U, Next', 'Sicko Mode', 'Girls Like You', 'In My Feelings', 'Nice For What', 'I Like It', 'Sad!', 'Psycho', 'This Is America', "God's Plan", 'Havana', 'Perfect']

In [7]:

print(artist_list)

['Lil Nas X Featuring Billy Ray Cyrus', 'Ariana Grande', 'Jonas Brothers', 'Lady Gaga & Bradley Cooper', 'Halsey', 'Post Malone & Swae Lee', 'Ariana Grande', 'Travis Scott', 'Maroon 5 Featuring Cardi B', 'Drake', 'Drake', 'Cardi B, Bad Bunny & J Balvin', 'XXXTENTACION', 'Post Malone Featuring Ty Dolla $ign', 'Childish Gambino', 'Drake', 'Camila Cabello Featuring Young Thug', 'Ed Sheeran']

In [8]:
print(date_list)

['2019-06-29', '2019-03-30', '2019-03-09', '2019-03-02', '2019-01-19', '2019-01-12', '2018-12-29', '2018-12-01', '2018-11-03', '2018-09-15', '2018-07-07', '2018-06-30', '2018-06-23', '2018-06-09', '2018-05-19', '2018-04-07', '2018-01-20', '2018-01-13']

In [13]:
summary_df=pd.DataFrame({"Title": title_list,
                        "Artist": artist_list,
                        "Date": date_list})
summary_df.head()

           Title                               Artist        Date
0  Old Town Road  Lil Nas X Featuring Billy Ray Cyrus  2019-06-29
1        7 Rings                        Ariana Grande  2019-03-30
2         Sucker                       Jonas Brothers  2019-03-09
3        Shallow           Lady Gaga & Bradley Cooper  2019-03-02
4     Without Me                               Halsey  2019-01-19

In [10]:

first_name=summary_df.Artist.str.split(expand=True,)[0]
first_name

               0         1          2          3       4     5       6
0            Lil       Nas          X  Featuring   Billy   Ray   Cyrus
1         Ariana    Grande       None       None    None  None    None
2          Jonas  Brothers       None       None    None  None    None
3           Lady      Gaga          &    Bradley  Cooper  None    None
4         Halsey      None       None       None    None  None    None
5           Post    Malone          &       Swae     Lee  None    None
6         Ariana    Grande       None       None    None  None    None
7         Travis     Scott       None       None    None  None    None
8         Maroon         5  Featuring      Cardi       B  None    None
9          Drake      None       None       None    None  None    None
10         Drake      None       None       None    None  None    None
11         Cardi        B,        Bad      Bunny       &     J  Balvin
12  XXXTENTACION      None       None       None    None  None    None
13          Post    Malone  Featuring         Ty   Dolla  $ign    None
14      Childish   Gambino       None       None    None  None    None
15         Drake      None       None       None    None  None    None
16        Camila   Cabello  Featuring      Young    Thug  None    None
17            Ed   Sheeran       None       None    None  None    None

In [11]:
summary_df_update3=pd.DataFrame({"Title": title_list,
                        "Artist": artist_list,
                        "First Name": first_name,
                        "Date": date_list})
summary_df_update3.head()

TypeError: 'int' object is not iterable

In [ ]:
summary_df_update3.to_csv('summary_df_update3.csv',index=False)